server_name         : Work Notebook
check_urgent_alerts : 1m 
check_regular_alerts: 60m 
send_error_period   : 10 # minute
send_urgent_period  : 10 # minute
start_clean_old_logs: 00:00:00
num_attempts_fail   : 10
num_logs_for_attach : 20
admin_emails        : [sorokin@oculeus.com] 

logger:
  loglevel: debug
  # logfile : alert-notification.log

  logrotation:
    maxsize   : 1
    maxbackups: 10

  logformatter:
    timestamp_format: 2006-01-02 15:04:05.000
    full_path_caller: false

postgres:
  host          : localhost
  port          : 5432
  database      : postgres
  schema        : logs_manager
  user          : postgres
  password      : postgres
  sslmode       : disable
  max_open_conns: 25

notification:
  enabled: [email, bitrix]

  email:
    visible_name: ALert Notification Service
    smtp_user   : monitor@oculeus.com
    smtp_pass   : 3nRPtxu89XKCuUF$2021
    smtp_host   : smtp.1und1.de
    smtp_port   : 587
    timeout     : 5s 
    # addresses   : sorokin@oculeus.com

  bitrix:
    host            : oculeus.bitrix24.eu
    user_token      : g76pbgrrl0w3dfae
    user_id         : 167 
    bot_id          : 171
    # bot_code        : 9x5gp1xb1g0sh0nj
    client_id       : dg3badlqc7x6v53e42sschpdd90xxo1c
    timeout         : 5s 
    lifetime_message: 48h
    use_notification: true
    admin_id        : 121
    admin_token     : 8xk2mupieukqprnx
    # addresses       : [121]

  telegram:
    host     : api.telegram.org
    token    : 5050037516:AAH7ARXYiighO50-6djxbq4ISOGrzm8eSqw
    timeout  : 5s 
    addresses: [1447091689]
